import java.awt.*;
import java.awt.event.*;
import javax.swing.*;


/**
 *
 * @author lenovo
 */
public class PilihGambarButton extends javax.swing.JFrame {

    /**
     * Creates new form PilihGambarButton
     */
   
    
    
    
    public PilihGambarButton() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPanel = new javax.swing.JPanel();
        htmlBT = new javax.swing.JButton();
        javaBT = new javax.swing.JButton();
        pythonBT = new javax.swing.JButton();
        exitBT = new javax.swing.JButton();
        imagePanel = new javax.swing.JPanel();
        htmlLB = new javax.swing.JLabel();
        javaLB = new javax.swing.JLabel();
        PythonLB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(375, 495));
        setMinimumSize(new java.awt.Dimension(375, 495));
        setPreferredSize(new java.awt.Dimension(390, 530));

        buttonPanel.setBackground(new java.awt.Color(0, 102, 102));
        buttonPanel.setMaximumSize(new java.awt.Dimension(269, 33));
        buttonPanel.setMinimumSize(new java.awt.Dimension(269, 33));

        htmlBT.setText("HTML");
        htmlBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                htmlBTActionPerformed(evt);
            }
        });
        buttonPanel.add(htmlBT);

        javaBT.setText("JAVA");
        javaBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                javaBTActionPerformed(evt);
            }
        });
        buttonPanel.add(javaBT);

        pythonBT.setText("PYTHON");
        pythonBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pythonBTActionPerformed(evt);
            }
        });
        buttonPanel.add(pythonBT);

        exitBT.setText("EXIT");
        exitBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTActionPerformed(evt);
            }
        });
        buttonPanel.add(exitBT);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.PAGE_START);

        imagePanel.setBackground(new java.awt.Color(153, 153, 153));
        imagePanel.setMaximumSize(new java.awt.Dimension(375, 499));
        imagePanel.setMinimumSize(new java.awt.Dimension(375, 499));
        imagePanel.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                imagePanelComponentAdded(evt);
            }
        });
        imagePanel.setLayout(new java.awt.CardLayout());

        htmlLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        htmlLB.setIcon(new javax.swing.ImageIcon("D:\\KULIAH\\BAHAN BAHAN & TUGAS MATA KULIAH\\Semester 5\\PBO 2\\Latihan 4\\PenampilGambar\\src\\img\\HtmlBook.jpg")); // NOI18N
        htmlLB.setToolTipText("null");
        htmlLB.setPreferredSize(new java.awt.Dimension(375, 499));
        imagePanel.add(htmlLB, "0");
        htmlLB.getAccessibleContext().setAccessibleName("0");

        javaLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        javaLB.setIcon(new javax.swing.ImageIcon("D:\\KULIAH\\BAHAN BAHAN & TUGAS MATA KULIAH\\Semester 5\\PBO 2\\Latihan 4\\PenampilGambar\\src\\img\\JavaBook.jpg")); // NOI18N
        imagePanel.add(javaLB, "1");
        javaLB.getAccessibleContext().setAccessibleName("1");

        PythonLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PythonLB.setIcon(new javax.swing.ImageIcon("D:\\KULIAH\\BAHAN BAHAN & TUGAS MATA KULIAH\\Semester 5\\PBO 2\\Latihan 4\\PenampilGambar\\src\\img\\PythonBook.jpg")); // NOI18N
        PythonLB.setMaximumSize(new java.awt.Dimension(375, 499));
        PythonLB.setMinimumSize(new java.awt.Dimension(375, 499));
        PythonLB.setPreferredSize(new java.awt.Dimension(375, 499));
        imagePanel.add(PythonLB, "2");

        getContentPane().add(imagePanel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void htmlBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_htmlBTActionPerformed
        CardLayout cl = (CardLayout) (imagePanel.getLayout());
        cl.show(imagePanel, "0");
    }//GEN-LAST:event_htmlBTActionPerformed

    private void exitBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitBTActionPerformed

    private void javaBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_javaBTActionPerformed
        CardLayout cl = (CardLayout) (imagePanel.getLayout());
        cl.show(imagePanel, "1");
    }//GEN-LAST:event_javaBTActionPerformed

    private void imagePanelComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_imagePanelComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_imagePanelComponentAdded

    private void pythonBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pythonBTActionPerformed
        CardLayout cl = (CardLayout) (imagePanel.getLayout());
        cl.show(imagePanel, "2");
    }//GEN-LAST:event_pythonBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PilihGambarButton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PythonLB;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton exitBT;
    private javax.swing.JButton htmlBT;
    private javax.swing.JLabel htmlLB;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JButton javaBT;
    private javax.swing.JLabel javaLB;
    private javax.swing.JButton pythonBT;
    // End of variables declaration//GEN-END:variables
}
